name: 'Setup Node.js'
description: 'The wrapper for actions/setup-node'

inputs:
  node-version:
    default: '18'
    required: false
    description: 'The version of Node.js'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - uses: actions/cache@v3
      with:
        path: node_modules/.cache
        key: node-modules-cache-${{ runner.os }}
        lookup-only: ${{ github.ref_name != 'main' }}
