version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
    version_requirement_updates: 'increase_versions'
    automerged_updates:
      - match:
          update_type: 'all' # プロジェクトに応じて適切なパラメータに変える
    commit_message:
      prefix: 'deps'
